[package]
edition = "2021"
name = "enc28j60"
version = "0.1.0"

[dependencies]
embedded-hal = { version = "0.2", features = ["unproven"] }
cast = { version = "0.2", default-features = false }
byteorder = { version = "1.2", default-features = false }
